# Generated by Django 3.2.6 on 2021-08-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibleanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
