# Generated by Django 3.2.6 on 2021-08-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('survey', '0002_possibleanswer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='past_test_profile',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
