# Generated by Django 3.2.6 on 2021-08-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('survey', '0003_survey_past_test_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='past_test_profile',
            field=models.ManyToManyField(blank=True, null=True, to='users.Profile'),
        ),
    ]
