# Generated by Django 3.2.6 on 2021-08-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('survey', '0004_alter_survey_past_test_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='past_test_profile',
        ),
        migrations.CreateModel(
            name='ClosedSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answer', models.IntegerField()),
                ('wrong_answer', models.IntegerField()),
                ('percent', models.CharField(max_length=3)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='closed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.closedsurvey'),
        ),
    ]
