# Generated by Django 3.2.6 on 2021-08-17 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210817_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='closed',
        ),
        migrations.AddField(
            model_name='closedsurvey',
            name='closed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
    ]
