# Generated by Django 3.2.6 on 2021-08-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20210817_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedsurvey',
            name='percent',
            field=models.CharField(max_length=20),
        ),
    ]
